### ISSUE TITLE
Does not display new items in inventory after a dimension change

### ISSUE THREAD

**Issue by zanecek** [Furgl/Easy-Shulker-Access#2]
Unfortunately, I had to remove this mod from my private modpack - after traveling between dimensions, the collected items did not appear in the hotbar/inventory (but they were there). It was necessary to open the inventory and go into their slots for them to appear.

**Comment by alexlambson** [comment]
I can confirm I also have this issue. ~~It appears to only affect harvested blocks as my blaze farm still loaded blaze rods into my inventory~~. It affects all picked-up items.

Repro steps:

- Have some empty slots on your toolbar
- switch dimensions by going through a portal
- mine a block

**Expected:**

Block enters my inventory

**Actual:**

Block does not appear in my inventory.

**Workarounds:**

- I have noticed that opening a chest fixes the issue and the inventory will begin updating again.
- logging out and back in after dimension change

Opening a shulker box in my inventory via the mod appears to refresh my inventory, but my inventory still won't update afterward.

**Comment by Furgl** [comment]
This issue should be fixed in v1.1.1
Thank you for reporting it!

**Comment by alexlambson** [comment]
Cool! Thank you!

Sorry, I tried to find a fix to PR for you but I am not a Java dev and couldn't figure it out.
